[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[events]]
  event = "submission-created"
  handler = "netlify/functions/submission-created.js"

